### ISSUE TITLE
no such file or directory, yasnippet

### ISSUE THREAD

**Issue by SkiftCreative** [kootenpv/emp#3]
From a fresh install of emacs (brew, OSX), and setup of emp. I get the below error when all the packages are finished downloading. It also shows when opening a new window and starting emacs again. I am new to emacs to not sure where this breaks. But it seems like the plugins included are not configured correctly.

```
Warning (initialization): An error occurred while loading `/Users/shawn/.emacs':

File error: Cannot open load file, no such file or directory, yasnippet

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

my `~/.emacs` file:
```
(setq user-emacs-directory "~/.emp/")
(load (concat user-emacs-directory ".emacs.d/init.el"))
```

**Comment by kootenpv** [comment]
Thanks for posting the issue. Try creating `~/.emp/.emacs.d/yasnippets`, maybe that solves the issue?

**Comment by kootenpv** [comment]
Actually, here is the answer: http://stackoverflow.com/questions/14684971/cannot-open-load-file-yasnippet

**Comment by kootenpv** [comment]
I've done many fresh installs, so I wonder what specifically you might have done that caused this? Just install emacs? If you try reopening emacs once more, does it solve the problem?

**Comment by SkiftCreative** [comment]
I removed everything and tried again, and it seemed to work. So possibly an issue on my end downloading plugins? Not sure.
